{% set name = "dtool_config" %}
{% set reponame = "dtool-config" %}
{% set author = "jic-dtool" %}
{% set version = "0.2.0" %}
{% set sha256 = "9623ee832e79ef581c117ef92b43a2e1f77782aaeaf14cfd4572d1819a193418" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - setuptools
    - dtoolcore
    - dtool_cli

test:
  imports:
    - dtool_config
    - dtool_config.cli
    - dtool_config.utils
  commands:
    - dtool config --help

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'dtool CLI commands for configuring dtool settings'

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
