{% set name = "dtool_config" %}
{% set reponame = "dtool-config" %}
{% set author = "jic-dtool" %}
{% set version = "0.3.0" %}
{% set sha256 = "b9ce1059e084434276350f423180617c90b43e337d1b46211fdb5b0eb257df81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - setuptools
    - dtoolcore
    - dtool_cli

test:
  imports:
    - dtool_config
    - dtool_config.cli
    - dtool_config.utils
  commands:
    - dtool config --help

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'dtool CLI commands for configuring dtool settings'

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
