{% set name = "dtool_config" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-config/dtool-config-{{ version }}.tar.gz
  sha256: "1018372294a79a7b7053a8ab3a5c1ec7f9e5f17f4f15349d648bbd143ffcfa1e"

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore
    - dtool_cli

test:
  imports:
    - dtool_config
    - dtool_config.cli
    - dtool_config.utils
  commands:
    - dtool config --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-config
  license: MIT
  license_file: LICENSE.rst
  summary: 'dtool CLI commands for configuring dtool settings'
  doc_url: https://github.com/jic-dtool/dtool-config
  dev_url: https://github.com/jic-dtool/dtool-config

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
