travis:
  secure:
    BINSTAR_TOKEN: FwWQKKdwAe/7hetYeCjObRNcziym9aRR18rOucwKiZZnpW5sC1bplv1zqnq+g5po0rgBIJt+s+GJdDSxWeHpdq9u41f6MqTNDbtEt1lHchEfQ2+ZOs/wQ7Odgwp1wxvun/ZAVM5y6gLUEOEYDko12LrXRD60OLKCqQtsYTCe3S6o11/WUbFPk7yrMB+AD2gyFBSWMPOOpmUnT8pIUOdulakLXbJOTSjaEF347cOzV+xJjQtKeBQuDQCBbdRgMEzE/6E4GajK6lEvSTJ7gEqo9YG4EJbaUqAegCN6Dsf7FWngmM7NTTQ0MJxesXjCFUeYRvX7AX1P3bZRA/crItnyGAUoy4eK+C2hcPjw1cPnuHTk9l8TirMpuq8CxB9LjglSCciHwPUhKYd+ziw91uhxqlvkjb3cB5fse/0nMrPEp1HLSpE8E6pXTwZV4Tgabi/foij89sJtusWtcXPntxr9DY99t/FwI31K/iPrS1D3tcKcbcPDdHHshP/avDcrRvF1bbPZXzkfNu4BSS2aVmDf/kFNAk3/nOpZXbcSp7t0i1MmqYw/V32hnALjXTHxzkE6nPWqv/8ic2vV7UXD9rttUt/pWyBJVpOFghEdZSSr09kwjEzACLX8FAuVGD0dGFqBdXCLbQHzyrn10EW7U2MfrNNOpgYtzuJIAUD2Apc6d88=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
